# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Carolyn Van Slyck
author: Carolyn Van Slyck
email:
description: ># Carolyn is a software developer from Chicago,
  though one day she hopes to escape to the Pacific Northwest in search of faster internet,
  free-range kittens and respite from snow blowers. She loves all things automation,
  developer tools and anything that will make her fellow developers lives easier.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carolynvanslyck.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:title/
category_dir: blog/categories
feed:
  path: atom.xml

twitter_username: carolynvs
github_username:  carolynvs


# Build settings
gems:
  - jekyll-feed
markdown: kramdown
exclude:
  - vendor/bundle
  - Dockerfile
  - Gemfile*
  - Makefile
  - Rakefile
  - scripts
  - manifests
  - talk
keep_files:
  - talk
timezone: America/Chicago
recent_posts: 5
