baseURL: https://carolynvanslyck.com
disablePathToLower: true
languageCode: en-us
title: Carolyn Van Slyck
theme: cvs
RSSLink: "https://carolynvanslyck.com/blog/index.xml"
permalinks:
  blog: /blog/:year/:month/:slug/
buildFuture: true

params:
  image: images/carolynvs.twitter.jpg
