[Settings]
  ID = "carolynvanslyck"

[build]
  publish = "public"
  command = "hugo -b $DEPLOY_PRIME_URL"

[build.environment]
  HUGO_VERSION = "0.48"

[[redirects]]
  from = "/index.xml"
  to = "/blog/index.xml"
